languageCode = "fr"
languageName = "ðŸ‡«ðŸ‡· FranÃ§ais"
languageDirection = "ltr"
weight = 2

title = "Mon portefolio"
copyright = "Copyright Alix ANNERAUD. Utilise Hugo avec le thÃ¨me Congo."

[params]
dateFormat = "2 January 2006"
description = "Le portefolio d'Alix ANNERAUD"

[author]
name = "Alix ANNERAUD"
image = "Images/Alix.png"
headline = "Ã‰tudiant en informatique."
links = [
  { email = "mailto:alix@anneraud.fr" },
  { github = "https://github.com/AlixANNERAUD" },
  { linkedin = "https://www.linkedin.com/in/alix-anneraud/" },
]
